### PR TITLE
Add example startup script to readme

### PR DESCRIPTION
**Pull request by Wferr**
im bad at these kinda things

### CODE REVIEW

**Comment by jkcclemens** [comment]
Looks like `#!/bin/bash` is on the same line as the `java` command?

Also, should avoid giving a real IRC server.

**Comment by Wferr** [comment]
Fixed.. i think.. Im horid at markdown.

**Comment by lol768** [comment]
FYI: If the code is inside a fenced code block (\`\`\`) you don't need to indent it.

**Comment by jkcclemens** [comment]
I'm updating it myself and then merging.

**Comment by Wferr** [comment]
tl;dr I suck at markdown.

**Pull request closed without merging**
